# setup environment
dist: jammy
language: go

branches:
  only:
  - master

notifications:
  email: false

git:
  depth: 5

# setup tests
env:
  global:
  - APM_TEST_PACKAGES='language-terraform'
  - ATOM_LINT_WITH_BUNDLED_NODE='true'

os: linux

# execute tests
install:
- curl -s https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash | sudo bash
before_script: circleci version
script: 'curl -s https://raw.githubusercontent.com/mschuchard/vagrant-boxes-docker-images/master/atom-build-package.sh | sh'
